USE [ebadascgl]
GO
/****** 对象:  Table [dbo].[bd_sbcs]    脚本日期: 03/10/2013 22:05:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[bd_sbcs](
	[bh] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[mc] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[xh] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[ID] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[ParentID] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[c1] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[c2] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[c3] [nvarchar](50) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK_BD_SBCS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'种类编号' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'bh'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'种类名称' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'mc'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'设备型号' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'xh'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ID' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'ID'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ParentID' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'ParentID'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'分类,设备、材料' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'c1'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'预留' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'c2'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'预留' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs', @level2type=N'COLUMN', @level2name=N'c3'

GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'设备型号库' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'bd_sbcs'
go

SET IDENTITY_INSERT [BD_SBTZ_ZL] ON
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('1','13','开关','3','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('2','14','刀闸','2','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('3','15','电抗器','3','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('4','9','变压器','4','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('5','18','电流互感器','5','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('6','19','电压互感器','6','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('7','8','电容器','4','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('8','511','阻波器','8','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('9','51','保护设备','9','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('10','16','避雷器','10','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('11','7','直流设备','11','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('12','1001','自动装置','12','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('13','1002','远动设备','13','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('14','1003','仪表屏','14','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('15','1004','其它','15','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('16','4','远程线路','16','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('17','1005','接地刀闸','17','','s',null,null)
Insert Into [BD_SBTZ_ZL] ([id],[dm],[mc],[jxzq],[pdm],[type],[c1],[c2]) Values('18','17','熔断器','18','','s',null,null)
SET IDENTITY_INSERT [BD_SBTZ_ZL] OFF

go

SET IDENTITY_INSERT [BD_SBTZ_SX] ON
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('1','13','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('30','13','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('31','13','a3','型号','1','3','是','','value','as|ab|ac','是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('135','13','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('136','13','a5','出厂日期','2','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('137','13','a6','投产日期','2','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('138','13','a7','生产厂家','1','7','是','','value','厂家1|ab|ac','是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('139','14','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('140','14','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('141','14','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('142','14','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('143','14','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('144','14','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('145','14','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('146','15','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('147','15','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('148','15','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('149','15','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('150','15','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('151','15','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('152','15','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('153','9','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('154','9','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('155','9','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('156','9','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('157','9','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('158','9','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('159','9','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('160','18','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('161','18','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('162','18','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('164','18','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('165','18','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('166','18','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('167','19','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('168','19','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('169','19','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('170','19','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('171','19','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('172','19','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('173','19','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('174','8','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('175','8','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('176','8','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('177','8','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('178','8','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('179','8','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('180','8','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('181','511','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('182','511','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('183','511','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('184','511','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('185','511','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('186','511','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('187','511','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('188','51','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('189','51','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('190','51','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('191','51','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('192','51','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('193','51','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('194','51','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('195','16','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('196','16','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('197','16','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('198','16','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('199','16','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('200','16','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('201','16','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('202','9','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('205','9','a11','相数','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('206','9','a12','接线组别','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('207','9','a13','冷却方式','0','13','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('208','9','a14','调压','0','14','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('209','9','a15','油重','0','15','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('210','9','a16','总重(kg)','0','16','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('211','9','a17','空载电流(%)','0','17','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('212','9','a18','空载损耗(千瓦)','0','18','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('213','9','a19','机构形式','0','19','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('214','7','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('215','7','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('216','7','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('217','7','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('218','7','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('219','7','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('220','7','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('222','1001','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('223','1001','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('224','1001','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('225','1001','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('226','1001','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('227','1001','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('228','1002','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('229','1002','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('230','1002','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('231','1002','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('232','1002','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('233','1002','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('234','1002','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('235','1003','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('236','1003','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('237','1003','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('238','1003','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('239','1003','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('240','1003','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('241','1003','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('242','1004','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('243','1004','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('244','1004','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('245','1004','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('246','1004','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('247','1004','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('248','1004','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('253','4','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('254','4','a2','线路名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('255','4','a3','导线型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('256','4','a4','线路长度','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('257','4','a5','对侧单位','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('259','4','a6','保护配置','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('260','4','a7','备注','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('262','1004','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('263','1002','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('264','7','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('265','51','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('266','511','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('267','8','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('268','18','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('269','15','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('270','13','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('271','14','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('272','19','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('273','16','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('274','1003','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('275','1001','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('276','14','a9','额定电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('278','14','a11','机构形式','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('279','14','a12','总重','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('280','19','a9','总重','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('281','19','a10','变比','0','10','是','','value','','是','是','','')
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('283','18','a9','额定电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('284','18','a10','变比','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('285','18','a11','油重','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('286','18','a12','总重','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('298','13','a9','允许跳闸次数','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('300','13','a11','额定油压','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('302','13','a13','分闸闭锁压力','0','13','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('303','13','a14','补充压力','0','14','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('304','13','a15','额定气压','0','15','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('305','13','a16','补气压力','0','16','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('308','13','a19','总量','0','19','是','','value','','是','是','','')
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('310','16','a9','额定电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('311','16','a11','总重','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('312','1005','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('313','1005','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('314','1005','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('315','1005','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('316','1005','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('317','1005','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('318','1005','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('319','1005','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('320','1005','a9','额定电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('321','1005','a10','额定电流','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('322','1005','a11','机构形式','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('323','1005','a12','总重','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('324','1001','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('325','15','a9','额定电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('326','15','a10','额定电流','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('327','15','a11','额定容量','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('328','15','a12','额定电抗','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('330','511','a9','额定电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('331','511','a10','额定电流','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('332','511','a11','额定电感','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('333','511','a12','总重','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('334','17','a1','设备种类','0','1','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('335','17','a2','设备名称','0','2','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('336','17','a3','型号','0','3','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('337','17','a4','序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('338','17','a5','出厂日期','0','5','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('339','17','a6','投产日期','0','6','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('340','17','a7','生产厂家','0','7','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('341','17','a8','大修日期','0','8','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('342','100','a1','设备种类','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('343','100','a2','设备名称','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('344','100','a3','型号','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('345','100','a4','序号','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('346','100','a5','出厂日期','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('347','100','a6','投产日期','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('348','100','a7','生产厂家','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('349','100','a8','大修日期','0','0','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('393','13','a18','容量(kVA)','0','18','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('395','13','a21','开断电流（KA)','0','21','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('396','13','a22','机构型号','0','22','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('397','17','a9','级数','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('398','17','a10','容量','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('399','19','a11','级数','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('400','19','a12','容量','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('402','17','a11','额定电流','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('403','17','a12','额定电压','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('404','9','a20','额定容量（KVA）','0','20','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('405','9','a9','额定电压（KV）','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('406','9','a10','额定电流（A）','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('408','9','a22','油号','0','22','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('410','9','a23','短路损耗（KW）','0','23','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('411','16','a12','额定电流','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('412','8','a9','电压','0','9','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('413','8','a10','单台容量','0','10','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('414','8','a11','台数','0','11','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('415','8','a12','总容量','0','12','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('416','8','a13','放电线圈型号','0','13','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('417','8','a14','最大容量','0','14','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('419','8','a15','电压比','0','15','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('421','9','a24','负载损耗（KW）','0','24','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('422','9','a25','阻抗电压（%）','0','25','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('424','18','a15','额定短时（1S）热电流','0','15','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('425','18','a16','额定动稳定电流','0','16','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('427','18','a14','额定绝缘水平','0','14','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('428','18','a18','额定输出（VA）','0','18','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('429','18','a19','额定准确限值','0','19','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('430','9','a26','短路阻抗HV-LV I（%）','0','26','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('431','9','a27','短路阻抗HV-LV III（%）','0','27','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('432','9','a28','短路阻抗HV-LV IV（%）','0','28','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('433','9','a29','短路阻抗HV-MV III（%）','0','29','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('434','9','a30','短路阻抗MV-LV III（%）','0','30','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('435','9','a31','负载损耗HV-LV I（kW）','0','31','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('436','9','a32','负载损耗HV-LV III（kW）','0','32','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('437','9','a33','负载损耗HV-LV IV（kW）','0','33','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('438','9','a34','负载损耗HV-MV III（kW）','0','34','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('439','9','a35','负载损耗MV-LV III（kW）','0','35','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('440','9','a36','绝缘水平','0','36','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('441','18','a20','额定频率','0','20','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('442','18','a4','出厂序号','0','4','是','','value',null,'是','是',null,null)
Insert Into [BD_SBTZ_SX] ([id],[zldm],[sxcol],[sxname],[sxtype],[norder],[isvisible],[defaultvalue],[boxtype],[boxvalue],[isdel],[isedit],[c1],[c2]) Values('443','18','a13','准确级数','0','13','是','','value',null,'是','是',null,null)
SET IDENTITY_INSERT [BD_SBTZ_SX] OFF
go
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('员工总分汇总表(月)','Ebada.jhgl.UCJH_weekmanthz','Ebada.jhgl.dll','4','showM','','',1,0,'','ygzgz','20130225161337754156','20130210171939462250','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('员工总分汇总表(年)','Ebada.jhgl.UCJH_weekmanthz','Ebada.jhgl.dll','5','showY','','',1,0,'','ygzgz','20130228100057727250','20130210171939462250','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('财务出账','','','3','','','Mac_Folder_61',1,0,'','kcgl','20130304162334482118','20120728141819146875','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('材料明细分类账','Ebada.Kcgl.UC材料明细分类账','Ebada.Kcgl.dll','0','','','Mac_Folder_38',1,0,'','kcgl','20130304162404528801','20130304162334482118','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('变电管理','','','0','','','',1,0,'','','20130301152302368875','0','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('设备管理','Ebada.Scgl.Sbgl.UCBD_SBTZM','Ebada.Scgl.Sbgl.dll','10','','','',1,0,'','','20130301152325228250','20130301152302368875','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('设备属性设置','Ebada.Scgl.Sbgl.UCBD_SXM','Ebada.Scgl.Sbgl.dll','20','','','',1,0,'','','20130301152340728250','20130301152302368875','')
Insert Into [mModule] ([ModuName],[ModuTypes],[AssemblyFileName],[Sequence],[MethodName],[MethodParam],[IconName],[visiableFlag],[ActivityFlag],[IsCores],[Description],[Modu_ID],[ParentID],[Rights]) Values('设备参数','Ebada.Scgl.Sbgl.UCbd_bdcsM','Ebada.Scgl.Sbgl.dll','30','','','',1,0,'','','20130301152428228250','20130301152302368875','')
go
